create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (limite_de_like integer not null, status_proposta bit not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, sobrenome varchar(255) not null, tipo varchar(255) not null, primary key (id)) engine=InnoDB;
alter table proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, senha, email,tipo, status_proposta, limite_de_like) values ('11111111111', 'Josimar', '22555554444','josimar@gmail.com','1', false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta, limite_de_like) values ('22222222222', 'Maria', '22555554445','maria@gmail.com','1',false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta,limite_de_like) values ('33333333333', 'Jose', '22555554446','jose@gmail.com','1',false,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (limite_de_like integer not null, status_proposta bit not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, sobrenome varchar(255) not null, tipo varchar(255) not null, primary key (id)) engine=InnoDB;
alter table proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, senha, email,tipo, status_proposta, limite_de_like) values ('11111111111', 'Josimar', '22555554444','josimar@gmail.com','1', false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta, limite_de_like) values ('22222222222', 'Maria', '22555554445','maria@gmail.com','1',false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta,limite_de_like) values ('33333333333', 'Jose', '22555554446','jose@gmail.com','1',false,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (limite_de_like integer not null, status_proposta bit not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, sobrenome varchar(255) not null, tipo varchar(255) not null, primary key (id)) engine=InnoDB;
alter table proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, senha, email,tipo, status_proposta, limite_de_like) values ('11111111111', 'Josimar', '22555554444','josimar@gmail.com','1', false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta, limite_de_like) values ('22222222222', 'Maria', '22555554445','maria@gmail.com','1',false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta,limite_de_like) values ('33333333333', 'Jose', '22555554446','jose@gmail.com','1',false,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (limite_de_like integer not null, status_proposta bit not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, sobrenome varchar(255) not null, tipo varchar(255) not null, primary key (id)) engine=InnoDB;
alter table proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, senha, email,tipo, status_proposta, limite_de_like) values ('11111111111', 'Josimar', '22555554444','josimar@gmail.com','1', false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta, limite_de_like) values ('22222222222', 'Maria', '22555554445','maria@gmail.com','1',false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta,limite_de_like) values ('33333333333', 'Jose', '22555554446','jose@gmail.com','1',false,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (limite_de_like integer not null, status_proposta bit not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, sobrenome varchar(255) not null, tipo varchar(255) not null, primary key (id)) engine=InnoDB;
alter table proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, senha, email,tipo, status_proposta, limite_de_like) values ('11111111111', 'Josimar', '22555554444','josimar@gmail.com','1', false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta, limite_de_like) values ('22222222222', 'Maria', '22555554445','maria@gmail.com','1',false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta,limite_de_like) values ('33333333333', 'Jose', '22555554446','jose@gmail.com','1',false,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (limite_de_like integer not null, status_proposta bit not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, sobrenome varchar(255) not null, tipo varchar(255) not null, primary key (id)) engine=InnoDB;
alter table proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, senha, email,tipo, status_proposta, limite_de_like) values ('11111111111', 'Josimar', '22555554444','josimar@gmail.com','1', false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta, limite_de_like) values ('22222222222', 'Maria', '22555554445','maria@gmail.com','1',false,3);
insert into usuario (sobrenome, nome, senha, email, tipo, status_proposta,limite_de_like) values ('33333333333', 'Jose', '22555554446','jose@gmail.com','1',false,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
