create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
create table proposta (categoria tinyint check (categoria between 0 and 1), qtdlikes integer not null, id bigint not null auto_increment, user_id_id bigint not null, descricao varchar(255) not null, titulo varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (ativo bit not null, limite_de_like integer not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), sobrenome varchar(255), tipo varchar(255), primary key (id)) engine=InnoDB;
alter table if exists proposta add constraint UK_s6lurtjdne53vxbdlnm8dg23 unique (user_id_id);
alter table if exists proposta add constraint FKjd9emc4qh73nx9juyc8ktil0l foreign key (user_id_id) references usuario (id);
insert into usuario (sobrenome, nome, email,tipo, ativo, limite_de_like) values ('11111111111', 'Josimar','josimar@gmail.com','Professor', true,3);
insert into usuario (sobrenome, nome,email, tipo, ativo, limite_de_like) values ('22222222222', 'Maria','maria@gmail.com','Aluno',true,3);
insert into usuario (sobrenome, nome, email, tipo, ativo,limite_de_like) values ('33333333333', 'Jose','jose@gmail.com','Aluno',true,3);
insert into proposta (titulo,descricao,qtdlikes,user_id_id) values ('Titulo','descricao',1,1);
